name: Django                                

on:
  push:                                       
    branches:                                
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Whitesource Renovate Scan
        uses: renovatebot/github-action@v31.63.2
        with:
          configurationFile: example/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}

