name: Renovate

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Cosign
        uses: sigstore/cosign-installer@v1.1.0
      - name: cosigned
        run: echo -n "${{secrets.COSIGN_PASSWORD}}" | KO_PREFIX=gcr.io/projectsigstore/cosign/ci make sign-cosigned
